class_name SSDMCanvasAnimatorGlobal
extends RefCounted


const X_PROPERTY: String = "custom_minimum_size:x"
const Y_PROPERTY: String = "custom_minimum_size:y"
const SCALE_PROPERTY: String = "scale"
const MODULATE_A_PROPERTY: String = "modulate:a"
const MODULATE_PROPERTY: String = "modulate"
const ROTATION_PROPERTY: String = "rotation"
const POSITION_PROPERTY: String = "position"
const POSITION_X_PROPERTY: String = "position:x"

const SHADER_PARAMETER: String = "shader_parameter/"
const HUE_SHIFT_ENABLED: String = "hue_shift_enabled"
const HUE_SHIFT_SPEED: String = "hue_shift_speed"
const GLOW_ENABLED: String = "glow_enabled"
const GLOW_INTENSITY: String = "glow_intensity"
const GLOW_COLOR: String = "glow_color"
const SHIMMER_ENABLED: String = "shimmer_enabled"
const SHIMMER_SPEED: String = "shimmer_speed"
const SHIMMER_WIDTH: String = "shimmer_width"
const SHIMMER_BRIGHTNESS: String = "shimmer_brightness"
const OUTLINE_ENABLED: String = "outline_enabled"
const OUTLINE_COLOR: String = "outline_color"
const OUTLINE_SIZE: String = "outline_size"
const DISSOLVE_ENABLED: String = "dissolve_enabled"
const DISSOLVE_MODE: String = "dissolve_mode"
const DISSOLVE_PROGRESS: String = "dissolve_progress"
const DISSOLVE_SPREAD: String = "dissolve_spread"
const PULSE_ENABLED: String = "pulse_enabled"
const PULSE_SPEED: String = "pulse_speed"
const PULSE_MIN_ALPHA: String = "pulse_min_alpha"
const FLICKER_ENABLED: String = "flicker_enabled"
const FLICKER_SPEED: String = "flicker_speed"
const FLICKER_MIN: String = "flicker_min"
const BG_COLOR: String = "bg_color"
